### ISSUE TITLE
Missing git version tags

### ISSUE THREAD

**Issue by kloczek** [logpy/strategies#13]
Hi,

It would be good to add at least last `0.2.3` version tag.

Thx.

**Comment by kloczek** [comment]
Ping .. is it possible to add missig git tag?
sdist tar ball do not include test suite and use tagged tar ball is only way to build with test suite execution.
Please ..

**Comment by mrocklin** [comment]
Sorry, but I personally no longer maintain this repository.  I doubt that
anyone does

**Comment by kloczek** [comment]
Looks like last module `hypothesis` dropped use `strategies` so in meantime problem has been solved.

Closing.
